### ISSUE TITLE
Implement Code Action feature for Language Server 

### ISSUE THREAD

**Issue by NipunaMarcus** [ballerina-lang/language-server#103]
**Description:**
Add the [Code Action](https://microsoft.github.io/language-server-protocol/specification#textDocument_codeAction) feature for Ballerina language server.

**Comment by lankavitharana** [comment]
Created a new issue in repository - https://github.com/ballerina-lang/ballerina
issue - ballerina-lang/ballerina#4773
hence closing this issue
