### ISSUE TITLE
No content assistance for errors followed by throw keyword

### ISSUE THREAD

**Issue by NipunaMarcus** [ballerina-lang/language-server#104]
**Description:**

No content assistance for errors followed by throw keyword. 

```

function main(string[] args) {
    system:println("Hello, World!");
    error err = {msg:"Account with id: is not found"};
        try {
            **throw err;**
        }
        catch(error err22) {
            system:println("Error caught...");
        }finally {
            system:println("Finally...");
        }
}
```

**Related Issues:**

https://github.com/ballerinalang/composer/issues/4042

**Comment by lankavitharana** [comment]
Created a new issue in repository - https://github.com/ballerina-lang/ballerina
issue - ballerina-lang/ballerina#4772
hence closing this issue
