### ISSUE TITLE
Add Lock Statement Support for Completions

### ISSUE THREAD

**Issue by nadeeshaan** [ballerina-lang/language-server#112]
**Description:**
Need to support https://github.com/ballerinalang/ballerina/pull/4508

**Related Issues:**
https://github.com/ballerinalang/ballerina/pull/4508

**Comment by lankavitharana** [comment]
Created a new issue in repository - https://github.com/ballerina-lang/ballerina
issue - ballerina-lang/ballerina#4771
hence closing this issue
